# Generated by Django 4.1.3 on 2023-03-31 15:46

import ap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_add_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[ap.validators.file_size]),
        ),
    ]
